foreground               #EEE5E9
background               #121314
selection_foreground     #121314
selection_background     #E6AA68

cursor                   #EEE5E9
cursor_text_color        #121314

url_color                #7B8CDE

active_border_color      #191919
active_tab_foreground    #EEE5E9
active_tab_background    #515457
inactive_border_color    #191919
inactive_tab_foreground  #515457
inactive_tab_background  #121314

# black
color0   #121314
## grey - used by zsh-autosuggestions
color8   #515457

# red
color1   #E75A7C
color9   #E75A7C

# green
color2   #72BDA3
color10  #72BDA3

# yellow
color3   #E6AA68
color11  #E6AA68

# blue
color4   #7B8CDE
color12  #7B8CDE

# magenta
color5   #B799C8
color13  #B799C8

# cyan
color6   #C5DCFC
color14  #C5DCFC

# white
color7   #EEE5E9
color15  #EEE5E9
