# theme
include current-theme.conf

# settings
## window
window_padding_width 8
enabled_layouts tall:bias=70;full_size=1;mirrored=false,stack
window_border_width 1.5
## tab
tab_bar_style fade
tab_activity_symbol "* "
## cursor
cursor_shape block
shell_integration no-cursor
mouse_hide_wait -1
## font
font_family JetBrainsMono Nerd Font Mono
font_size 13.0
modify_font cell_height 130%
inactive_text_alpha 0.5
disable_ligatures always

# map
map ctrl+cmd+, load_config_file
map kitty_mod+x toggle_layout stack
map cmd+enter launch --cwd=current
